import streamlit as st
import sys
import os

# Ensure local imports work
DIR = os.path.dirname(os.path.abspath(__file__))
if DIR not in sys.path:
    sys.path.insert(0, DIR)

from lead_manager import (
    score_by_identifier, get_score_history, format_score_result, load_data,
    analyze_risk_with_gemini
)

def main():
    try:
        st.set_page_config(
            page_title="🎯 Lead Qualifier",
            page_icon="🎯",
            layout="wide"
        )
    except:
        pass

    st.title("🎯 Lead Qualifier")
    st.caption("Score carriers and companies by authority age, safety rating, and risk factors")
    
    # ... Copying Logic from original file ...
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        st.subheader("Score a Lead")
        
        # Search type selector
        search_type = st.radio("Search By:", ["USDOT or MC Number", "Company Name"], horizontal=True)
        
        if search_type == "USDOT or MC Number":
            identifier = st.text_input("Enter USDOT or MC Number", placeholder="1234567 or MC123456")
            search_by_name = False
        else:
            identifier = st.text_input("Enter Company Name", placeholder="ABC Trucking LLC")
            search_by_name = True
        
        if st.button("🔍 Score Lead", use_container_width=True):
            if identifier:
                with st.spinner("Fetching..."):
                    result = score_by_identifier(identifier, search_by_name=search_by_name)
                
                if "error" in result:
                    st.error(f"❌ {result['error']}")
                else:
                    score = result['score']
                    risk = result['risk_level']
                    emoji = result['risk_emoji']
                    carrier = result.get('carrier_data', {})
                    
                    c_score, c_risk = st.columns(2)
                    c_score.metric("Score", f"{score}/100")
                    c_risk.metric("Risk", f"{emoji} {risk}")
                    
                    st.divider()
                    st.subheader(carrier.get('legal_name', 'Unknown'))
                    
                    ic1, ic2 = st.columns(2)
                    ic1.write(f"**USDOT:** {carrier.get('dot_number')}")
                    ic2.write(f"**MC:** {carrier.get('mc_number')}")
                    
                    st.write("**Breakdown:**")
                    for item in result.get('breakdown', []):
                        st.write(f"- {item}")
                        
                    st.divider()
                    st.subheader("🤖 AI Risk Analysis")
                    
                    if st.button("🧠 Deep Vet this Carrier"):
                        with st.spinner("Consulting Risk Officer (Gemini)..."):
                            analysis = analyze_risk_with_gemini(carrier)
                            st.markdown(analysis)
                            st.caption("Auto-generated by Pocket Empire Intelligence")
    
    with col2:
        st.subheader("Recent Scores")
        history = get_score_history(10)
        for entry in reversed(history):
            res = entry.get('result', {})
            c = res.get('carrier_data', {})
            st.write(f"**{c.get('legal_name', 'Unknown')[:20]}**")
            st.caption(f"Score: {res.get('score')} | {entry.get('identifier')}")
            st.divider()

if __name__ == "__main__":
    main()
